fix typo

diff --git a/backsync b/backsync
--- a/backsync
+++ b/backsync
@@ -2,20 +2,23 @@
 
 ### Backup Script
 
-#dst_arg="${@: -1}"
+#
+# backsinc [-sfnzv*] <directory source> <directory target>
+#
+
 src_arg="$(($#-1))"
 dst_arg="$(($#-0))"
 # --
 src_arg="${!src_arg}"
 dst_arg="${!dst_arg}"
 
-if [[ -d "$src_arg" && -d "$dst_arg" ]]; then
-    PREFIX_SRC="./"
-    PREFIX_DST="$dst_arg"
-    DIR_TAR="$src_arg"/
+if [[ ! -z "$src_arg" && ! -z "$dst_arg" ]]; then
+    PREFIX_SRC="$src_arg"/
+    PREFIX_DST="$dst_arg"/
+    DIR_TAR=
 else
     PREFIX_SRC="../"
-    PREFIX_DST="/media/$USER/MARS/"
+    PREFIX_DST="/media/$USER/WAVED/"
     DIR_TAR="workInProgress/"
 fi
 
@@ -44,57 +47,70 @@ GREPGIT="1" # don't show .git/* files
 
 ##############
 ### Args Parse
-nbarg=$#
-for i in `seq 1 $nbarg`; do
+NBARG=$#
+for i in `seq 1 $NBARG`; do
     arg=$1
-    if [ "$arg" != "" ]; then
-        if [ "$arg" == "-s" ]; then
-            OPTS="$OPTS --dry-run" && FORCE="1"
-            SIMUL="1"
-        elif [ "$arg" == "-v" ]; then
-            VERBOSE="-v -i"
-        elif [ "$arg" == "-vv" ]; then
-            VERBOSE="-vv -i"
-        elif [ "$arg" == "--purge" ]; then # remove some
-            PURGE="1"
-        elif [ "$arg" == "-n" -o "$arg" == "--net" ]; then
-            PREFIX_DST=$PREFIX_DST_NET
-            FILTER_F="--exclude-from=.rsync_include_expe"
-            #FILTER_F="--exclude-from=.rsync_include_net"
-            NET="1"
-        elif [ "$arg" == "--down" ]; then # update from backup
-            DOWN="1"
-        elif [ "$arg" == "-f" ]; then # force the backup
-            FORCE="1"
-        elif [ "$arg" == "-z" -o "$arg" == "--compress" ]; then # force the backup
-            COMPRESS="--compress"
-        elif [ "$arg" == "--safe" ]; then # don't remove anything
-            OPTS="$OPTS --max-delete=0"
-        elif [ "$arg" == "--size" ]; then # size only
-            OPTS="$OPTS --size-only"
-        elif [ "$arg" == "--nogrep" ]; then # size only
-            GREPGIT="0"
-        elif [ "$arg" == "-ss" -o "$arg" == "--size" ]; then # simul + size of files
-            OPTS="$OPTS --dry-run"
-            FORCE="1"
-            SIMUL="2"
-        #elif [ "$arg" == "--exclude" ]; then # exclusion regex
-        elif [ "$arg" == "-exreg" ]; then # exclusion regex
-            OPTS="--exclude=$2"
-            shift
-        elif [ "$arg" == "--checksum" ]; then # exclusion regex
-            OPTS="$OPTS --checksum"
-            shift
-        elif [ "$arg" == "--make" ]; then
-            Make="1"
-        elif [ "$arg/" == "$DIR_TAR" ]; then
-            continue
-        else
-            echo "$0 error [exiting]"
-            exit 1
-        fi
+    if [ "$arg" == "" ]; then
+        continue
+    elif [ "$arg/" == "$DIR_TAR" -o "$arg/" == "$PREFIX_SRC" -o "$arg/" == "$PREFIX_DST" ]; then
+        continue
+    elif [ "$arg" == "-s" ]; then
+        OPTS="$OPTS --dry-run" && FORCE="1"
+        SIMUL="1"
+    elif [ "$arg" == "-v" ]; then
+        VERBOSE="-v -i"
+    elif [ "$arg" == "-vv" ]; then
+        VERBOSE="-vv -i"
+    elif [ "$arg" == "--purge" ]; then
+        # remove some
+        PURGE="1"
+    elif [ "$arg" == "-n" -o "$arg" == "--net" ]; then
+        PREFIX_DST=$PREFIX_DST_NET
+        FILTER_F="--exclude-from=.rsync_include_expe"
+        #FILTER_F="--exclude-from=.rsync_include_net"
+        NET="1"
+    elif [ "$arg" == "--down" ]; then
+        # update from backup
+        DOWN="1"
+    elif [ "$arg" == "-f" ]; then
+        # force the backup
+        FORCE="1"
+    elif [ "$arg" == "-z" -o "$arg" == "--compress" ]; then
+        # force the backup
+        COMPRESS="--compress"
+    elif [ "$arg" == "--safe" ]; then
+        # don't remove anything
+        OPTS="$OPTS --max-delete=0"
+    elif [ "$arg" == "--size" ]; then
+        # size only
+        OPTS="$OPTS --size-only"
+    elif [ "$arg" == "--nogrep" ]; then
+        # font grep exclude git files
+        GREPGIT="0"
+    elif [ "$arg" == "-ss" -o "$arg" == "--size" ]; then
+        # simul + size of files
+        OPTS="$OPTS --dry-run"
+        FORCE="1"
+        SIMUL="2"
+    elif [ "$arg" == "-exreg" ]; then
+        # exclusion regex
+        OPTS="--exclude=$2"
+        shift
+    elif [ "$arg" == "--checksum" ]; then
+        OPTS="$OPTS --checksum"
+        shift
+    elif [ "$arg" == "--make" ]; then
+        Make="1"
+    else
+        echo "PREFIX_SRC=$PREFIX_SRC"
+        echo "PREFIX_DST=$PREFIX_DST"
+        echo "DIR_TAR=$DIR_TAR"
+        echo -e "$0 error for: ($arg)\n[exiting]"
+        exit 1
     fi
+
     shift
+
 done
 
 ### Remove some obsolete file before backup
@@ -109,19 +125,11 @@ if [ "$DOWN" == "1" ]; then
     PREFIX_SRC="$PREFIX_DST"
     PREFIX_DST="$TMP_SRC"
     #FILTER="$FILTER --exclude=/backup.sh"
-    tmp_h="$HOOK1"
-    hook1="$HOOK2"
-    hook2="$tmp_h"
 fi
 
 ### Set path target name
-if [ -z "$hook1" -a -z "$hook2" ]; then
-    DIR_TAR1="$DIR_TAR"
-    DIR_TAR2="$DIR_TAR"
-else
-    DIR_TAR1="$hook1"
-    DIR_TAR2="$hook2"
-fi
+DIR_TAR1="$DIR_TAR"
+DIR_TAR2="$DIR_TAR"
 
 if [ "$FORCE" == "0" ]; then
     echo "[warning dammages: use -f]"
@@ -133,7 +141,7 @@ OPTS="$OPTS $VERBOSE $COMPRESS $REMOTE $FILTER $FILTER_F"
 
 PADD=$(echo "--"$a{1..20}e)
 echo -e "$PADD\n[ Rsync Stage ...]"
-if [ "$SIMUL" == "2" ]; then #XULGet file size 
+if [ "$SIMUL" == "2" ]; then #XULGet file size
     echo "[ Simulation ]"
     RES=`/usr/bin/rsync ${OPTS} "${PREFIX_SRC}${DIR_TAR1}" "${PREFIX_DST}${DIR_TAR2}"`
     RES2=$RES
@@ -156,7 +164,7 @@ else
     if [ "${GREPGIT}" == "1" ]; then
         /usr/bin/rsync ${OPTS} "${PREFIX_SRC}${DIR_TAR1}" "${PREFIX_DST}${DIR_TAR2}" | grep -vE "\.git"
     else
-        /usr/bin/rsync ${OPTS} "${PREFIX_SRC}${DIR_TAR1}" "${PREFIX_DST}${DIR_TAR2}" 
+        /usr/bin/rsync ${OPTS} "${PREFIX_SRC}${DIR_TAR1}" "${PREFIX_DST}${DIR_TAR2}"
     fi
     echo "/usr/bin/rsync ${OPTS} ${PREFIX_SRC}${DIR_TAR1} ${PREFIX_DST}${DIR_TAR2}"
 fi
